-- Creation de tables

CREATE TABLE CLIENT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ADRESSE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID) FOREIGN KEY (ADRESSE) REFERENCES ADRESSE(ID)
);

CREATE TABLE RESERVATION (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CLIENT INT NOT NULL,
    ID_VOITURE INT NOT NULL,
    STARTDATE DATETIME NOT NULL,
    ENDDATE DATETIME NOT NULL,
    PRIMARY KEY (ID) FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID) FOREIGN KEY (ID_VOITURE) REFERENCES VOITURE(ID)
);

CREATE TABLE ADRESSE (
    ID INT NOT NULL AUTO_INCREMENT,
    NUMERO INT NOT NULL,
    RUE VARCHAR(255) NOT NULL,
    VILLE VARCHAR(255) NOT NULL,
    PROVINCE VARCHAR(255) NOT NULL,
    PAYS VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE VOITURE (
    ID INT NOT NULL AUTO_INCREMENT,
    MARQUE VARCHAR(255) NOT NULL,
    MODELE VARCHAR(255) NOT NULL,
    ANNEE INT NOT NULL,
    COULEUR VARCHAR(255) NOT NULL,
    IS_RESERVED BOOLEAN NOT NULL,
    PRIX INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PAIEMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CLIENT INT NOT NULL,
    ID_RESERVATION INT NOT NULL,
    MONTANT INT NOT NULL,
    PRIMARY KEY (ID) FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID) FOREIGN KEY (ID_RESERVATION) REFERENCES RESERVATION(ID)
);

-- Insertion de données dans les tables

INSERT INTO CLIENT (
    ID,
    NAME,
    LASTNAME,
    EMAIL,
    PASSWORD,
    ADRESSE
) VALUES (
    '1',
    'Dragomir',
    'Mihai',
    'admin@gmail.com',
    'admin',
    '1080 Rue LaRiviere'
);

INSERT INTO CLIENT (
    ID,
    NAME,
    LASTNAME,
    EMAIL,
    PASSWORD,
    ADRESSE
) VALUES (
    '2',
    'Jorge',
    'Fernandez',
    'admin2@gmail.com',
    'admin2',
    '1079 Rue LeFleuve'
);

INSERT INTO VOITURE(
    ID,
    MARQUE,
    MODELE,
    ANNEE,
    IS_RESERVED,
    PRIX
) VALUES(
    '1',
    'Toyota',
    'Corolla',
    '2002',
    'FALSE',
    '5000'
) 

INSERT INTO VOITURE( ID, MARQUE, MODELE, ANNEE, IS_RESERVED, PRIX
) VALUES(
    '2',
    'Nissan',
    'Altima',
    '2007',
    'FALSE',
    '7000'
)

--